
import type { Metadata } from "next";


import { AppProviders } from "./providers";
import { GetSidebarState } from "@/components/Sidebar/actions";
import Sidebar from "@/components/Sidebar";
import PageWrapper, { MainWrapper } from "@/components/layout/Wrappers";
import FooterApp from "@/components/layout/Footer";
import NavBar from "@/components/NavBar";


export const metadata: Metadata = {
    title: "App Dashboard",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const sidebarCookie = await GetSidebarState();
    const sidebarOpen = sidebarCookie && sidebarCookie.value === 'true' ? true : false;

    return (
        <AppProviders sidebarOpen={sidebarOpen}>
            <div className="flex w-full relative bg-muted/40">
                <Sidebar />
                <MainWrapper>
                    <NavBar />
                    <PageWrapper>
                        {children}
                    </PageWrapper>
                    <FooterApp />
                </MainWrapper>
            </div>
        </AppProviders>
    );
}
