
import type { Metadata } from "next";
import { Poppins } from 'next/font/google';

// Import Styles
import '../sass/index.scss';

// Import Utils
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/NextThemes/provider";

// Fonts
const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    style: 'normal',
    subsets: ['latin'],
    variable: "--font-poppins",
})

export const metadata: Metadata = {
    title: "Starter Pack",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(
                "min-h-screen bg-background antialiased",
                poppins.className
            )}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
