
import type { Metadata } from "next";
import { Poppins } from 'next/font/google';

// Import Styles
import '../sass/index.scss';

// Import Utils
import { cn } from "@/lib/utils";
import Sidebar from "@/components/Sidebar";
import { AppProviders } from "./providers";
import { GetSidebarState } from "@/components/Sidebar/actions";
import PageWrapper, { MainWrapper } from "@/components/layout/Wrappers";
import FooterApp from "@/components/layout/Footer";
import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/components/NextThemes/provider";

// Fonts
const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    style: 'normal',
    subsets: ['latin'],
    variable: "--font-poppins",
})

export const metadata: Metadata = {
    title: "Starter Pack",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const sidebarCookie = await GetSidebarState();
    const sidebarOpen = sidebarCookie && sidebarCookie.value === 'true' ? true : false;

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(
                "min-h-screen bg-background antialiased",
                poppins.className
            )}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AppProviders sidebarOpen={sidebarOpen}>
                        <div className="flex w-full relative bg-muted/40">
                            <Sidebar />
                            <MainWrapper>
                                <NavBar />
                                <PageWrapper>
                                    {children}
                                </PageWrapper>
                                <FooterApp />
                            </MainWrapper>
                        </div>
                    </AppProviders>
                </ThemeProvider>
            </body>
        </html>
    );
}
